### ISSUE TITLE
Starting order of lcdsmartie

### ISSUE THREAD

**Issue by duck7000** [vavruska/kodi4smartie#1]
hi

First off all a big thanks for your work!

But i have a question
I use this plugin with lcdsmartie and kodi but i'm wondering what the best starting order would be?
I'm also using launcher4kodi to pass the windows explorer and start kodi as shell

Like imon, lcdsmartie, kodi
or imon, kodi, lcdsmartie

Maybe it doesn't matter?

Ed

**Comment by vavruska** [comment]
It shouldn't matter as the plugin wont try to connect to kodi until the
first $dll command, and if it isnt available then it will just continue to
retry. I am not sure what imon does though.

**Comment by duck7000** [comment]
Thank you for the quick answer!

Imon is the software needed for the display and ir receiver for my antec fusion htpc case.
Lcdsmartie need this to be installed otherwise it won't work.

Ed

**Comment by duck7000** [comment]
I have one other issue

It would be nice to know that vc++2015 x86 runtime is needed to run the plugin..
It took me a few hours to figure it out

Could you add this to the wiki please?
It saves others from spending hours searching

**Comment by vavruska** [comment]
Updated the wiki
