### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by duck7000** [vavruska/kodi4smartie#2]
Hi

Is it possible to get the icons working on imon lcd display?

Like the video and audio type and audio channels

I found this info on the net and it looks promising, although it is for sagetv..

> Using the Soundgraph iMON LCD's ICONS with LCDsmartie
> -----------------------------------------------------
> iMON_OEM_LCD.dll v0.4 by dgbruce
> --------------------------------
> 
> To use the LCD's ICONS with LCD smartie, the iMON_OEM_LCD.dll used to drive the display
> must be v0.04 or higher.
> 
> Because other LCD/VFD displays commonly used with LCDsmartie do not have on screen icons, 
> and only support between 1 and 4 status L.E.D.s, we can not use the "accepted" method of using GPOs.
> Some of the other displays support up to 4 cooling fans, and are able to control the speed in 256
> increments.
> This allows us to use the fan control interface in LCDsmartie to control the Icons.
> 
> To control an icon, you call the "Fan" function from the "Actions" menu.
> 
> The "Fan" function is as follows:
> 
>           Fan(Function,Icon) where Function = 1 to 3 - 1 (turn the icon OFF), 2 (turn the icon ON), 3 (make the icon FLASH)
>                                        Icon = 0 to 54 (The Icon Index as outlined in the table below)
> 
> for example: to turn on the REC icon when SageTV is recording a show you would enter:
> 
>         IF    $dll(MizookLcd.dll,1,1,1)    >    0    then    Fan(2,34)
> 
> as an action.
> 
> *MizookLcd.dll is an LCDsmartie plugin by "cslatt" that retrieves status information from SageTV via
> the External Status Plugin by "neilm", and is available at http://mizook.com/lcd/. You can also get
> similar functionality with the Sage plugin for LCDsmartie (sage.dll) by "AndersNolberger", available at
> http://www.nolberger.se/Sage/LCDSmartie/. (NOTE: all nicknames are SageTV forum usernames!)
> 
> To turn the icon off, you would add:
> 
>         IF    $dll(MizookLcd.dll,1,1,1)    =    0    then    Fan(1,34)
> 
> as another action.
> 
> 
> 
> ICONS Index
> -----------
>  
>  0) L           1) NEWS        2) WEB         3) TV
>  4) CD/DVD      5) PHOTO       6) MOVIE       7) MUSIC
> 
>  8) RR          9) SPDIF      10) RL         11) SR         
> 12) LFE        13) SL         14) R          15) C
>  
> 16) DIVX       17) MPG        18) SCR2       19) SCR1
> 20) HDTV       21) TV         22) FIT        23) SRC
>  
> 24) OGG        25) MP3        26) WMA        27) DTS
> 28) AC3        29) MPG        30) WMV        31) XVID
> 
> 32) TIME       33) VOL        34) REC        35) ALARM
> 36) SFL        37) REP        38) WAV        39) WMA
>  
> 40) DISK Top Right            41) DISK Middle Right
> 42) DISK Bottom Right         43) DISK Bottom
> 44) DISK Bottom Left          45) DISK Middle Left
> 46) DISK Top Left             47) DISK Top
> 
> 48) DISK Bottom Crescent
> 
> 50) FULL DISK (all segments 40 through 47)
> 51) FULL DISK rotating clockwise(all but one segment of 40 through 47)
> 52) FULL DISK rotating clockwise(one segment of 40 through 47)
> 53) FULL DISK rotating counter-clockwise(all but one segment of 40 through 47)
> 54) FULL DISK rotating counter-clockwise(one segment of 40 through 47)

I found this link to be interesting as well:
[https://emby.media/community/index.php?/topic/31356-plugin-for-lcdvfd-screens-windows-imon-replacement-using-frontview-server-plugin/](url)

the imon oem dll v0.0.5 can be found in this forum, it includes the above text:
[https://forums.sagetv.com/forums/showthread.php?t=26053&page=2](url)

I don't know anything about c++ so i can't help or do it myself

**Comment by vavruska** [comment]
It looks quite interesting. I do not have an imon vfd so this will probably not be implemented as I have no way of testing.
